# Generated by Django 4.0.1 on 2022-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_appointment_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
