# Generated by Django 4.0.1 on 2022-03-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
