# Generated by Django 4.0.1 on 2022-03-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
