# Generated by Django 4.0.1 on 2022-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_appointment_date_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_type',
            field=models.CharField(choices=[('O', 'online'), ('F', 'Offline')], default='F', max_length=5),
        ),
    ]
