# Generated by Django 4.0.1 on 2022-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_patientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfile',
            name='details',
            field=models.CharField(default='Type Advice..', max_length=200),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='email',
            field=models.CharField(default='Type Patient Email..', max_length=50),
        ),
    ]
