# Generated by Django 4.0.1 on 2022-03-27 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_patientfile_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='To email Happy Life Clinic', max_length=255, unique=True, verbose_name='Email')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, help_text='H Clinicletter list', verbose_name='Happy Life Clinic')),
                ('delete_link', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Email User',
                'verbose_name_plural': 'Email Users',
            },
        ),
    ]
