# Generated by Django 4.0.1 on 2022-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_mailtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='delete_link',
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(help_text='To email Happy Life Clinic', max_length=255, verbose_name='Email'),
        ),
    ]
