# Generated by Django 4.0.1 on 2022-03-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_mail_delete_link_alter_mail_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtext',
            old_name='users',
            new_name='Users',
        ),
    ]
