# Generated by Django 4.0.1 on 2022-03-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_users_mailtext_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
