# Generated by Django 4.0.1 on 2022-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_users_mailtext_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtext',
            old_name='user',
            new_name='Users',
        ),
        migrations.AddField(
            model_name='mail',
            name='delete_link',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mailtext',
            name='attachment',
            field=models.FileField(upload_to=''),
        ),
    ]
