# Generated by Django 4.0.1 on 2022-03-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_user_mailtext_users_mail_delete_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtext',
            name='attachment',
            field=models.CharField(default='Type Patient prescription..', max_length=50),
        ),
    ]
