# Generated by Django 4.0.1 on 2022-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_mail_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
