# Generated by Django 4.0.1 on 2022-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_mail_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Camp',
        ),
        migrations.AlterField(
            model_name='mailtext',
            name='attachment',
            field=models.CharField(default='Type Patient prescription..', max_length=250),
        ),
    ]
