# Generated by Django 4.0.1 on 2022-03-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_camp_camp_check_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtext',
            old_name='Users',
            new_name='users',
        ),
    ]
