# Generated by Django 4.0.1 on 2022-03-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date',
            new_name='datetime',
        ),
    ]
