# Generated by Django 4.0.1 on 2022-03-31 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='User',
            field=models.ManyToManyField(help_text='user', related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
