# Generated by Django 4.0.1 on 2022-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
