# Generated by Django 4.0.1 on 2022-03-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_type',
            field=models.CharField(choices=[('O', 'online'), ('F', 'Offline')], default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
