# Generated by Django 4.0.1 on 2022-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_appointment_app_type_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
