# Generated by Django 4.0.1 on 2022-04-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_appointment_app_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='send_it',
        ),
    ]
