# Generated by Django 4.0.1 on 2022-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_mailtext_send_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
