# Generated by Django 4.0.1 on 2022-04-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_camp_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camp',
        ),
    ]
