# Generated by Django 4.0.1 on 2022-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_camp_camp_check_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Camp_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
