# Generated by Django 4.0.1 on 2022-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_camp_camp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='Camp_name',
            field=models.CharField(default='Camp', max_length=50),
        ),
    ]
